trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g expo-cli
    expo login -u mixserrm999@gmail.com -p mixserrm2547Apple
    expo build:ios
  displayName: 'Expo Build IPA'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$HOME/.expo/ios-builds'  # Adjust path if necessary
    artifactName: 'ipa'
    publishLocation: 'Container'
